server.port=8085
spring.application.name=athena
spring.output.ansi.enabled=ALWAYS
server.servlet.context-path=/api/v1

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.public.key=classpath:pub.key
jwt.private.key=classpath:app.key
